### ISSUE TITLE
IndexOutOfBoundsException on Sample App Map Activity

### ISSUE THREAD

**Issue by ekigamba** [onaio/kujaku#174]
Steps to replicate:

1. Open Kujaku Sample app
2. Click on **Open Map Activity**
3. Click on one the red circle feature below the **Mulele Road** text

This happens on the sample app with the m-spray data
The app crashes with the following log:

```
java.lang.IndexOutOfBoundsException: Invalid index 16, size is 16
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:260)
        at java.util.ArrayList.get(ArrayList.java:313)
        at io.ona.kujaku.adapters.InfoWindowAdapter.focusOnPosition(InfoWindowAdapter.java:108)
        at io.ona.kujaku.activities.MapActivity.scrollToInfoWindowPosition(MapActivity.java:482)
        at io.ona.kujaku.activities.MapActivity.showInfoWindowListAndScrollToPosition(MapActivity.java:476)
        at io.ona.kujaku.activities.MapActivity.focusOnFeature(MapActivity.java:580)
        at io.ona.kujaku.activities.MapActivity.focusOnFeature(MapActivity.java:595)
        at io.ona.kujaku.activities.MapActivity.onMapClick(MapActivity.java:450)
        at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnMapClickListeners(MapGestureDetector.java:908)
        at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onSingleTapConfirmed(MapGestureDetector.java:343)
        at com.mapbox.android.gestures.StandardGestureDetector$1.onSingleTapConfirmed(StandardGestureDetector.java:81)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5765)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
```

**Comment by ekigamba** [comment]
This is a duplicate of https://github.com/onaio/kujaku/issues/190

Permanently move to https://github.com/onaio/kujaku/issues/190
