### ISSUE TITLE
Crashing on Android api > 24 when trying to start MapboxOfflineDownloaderService.

### ISSUE THREAD

**Issue by Balcan** [onaio/kujaku#326]
Hi! I'm having this crash in several devices with Android 8:

```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } in io.ona.kujaku.receivers.KujakuNetworkChangeReceiver@39ceec7
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1401)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6746)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

It is happening when trying to start the MapboxOfflineowloaderService as it is using the .startService instead of .startForegroundService.

Don't know if I am missing something.
This is how we init the library:

```
        KujakuLibrary.setEnableMapDownloadResume(true);
        KujakuLibrary.init(this);
```

Thank you!

**Comment by ekigamba** [comment]
@Balcan Sorry for the late reply. I recently realized that I was my notification settings for this repo were off(I was not watching). 

Kindly disable the map-download-resumption.

The following initialisation should suffice

```
        KujakuLibrary.init(this);
```

Kindly also follow this https://github.com/onaio/kujaku/blob/master/sample/src/main/java/io/ona/kujaku/sample/MyApplication.java#L37

Get back in case of anything else
