### ISSUE TITLE
Error on reconnect or disconnect to internet

### ISSUE THREAD

**Issue by Kigamba** [onaio/kujaku#81]
```
java.lang.RuntimeException: Unable to start service io.ona.kujaku.services.MapboxOfflineDownloaderService@ad5aef2 with Intent { cmp=io.ona.kujaku.test/io.ona.kujaku.services.MapboxOfflineDownloaderService (has extras) }: java.lang.IllegalStateException: Call 'Realm.init(Context)' before calling this method.

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4145)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at android.app.ActivityThread.access$2400(ActivityThread.java:229)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Call `Realm.init(Context)` before calling this method.

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at io.realm.Realm.getDefaultInstance(Realm.java:327)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at io.ona.kujaku.services.MapboxOfflineDownloaderService.getNextTask(MapboxOfflineDownloaderService.java:391)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at io.ona.kujaku.services.MapboxOfflineDownloaderService.performNextTask(MapboxOfflineDownloaderService.java:223)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at io.ona.kujaku.services.MapboxOfflineDownloaderService.onStartCommand(MapboxOfflineDownloaderService.java:139)

01-27 05:52:09.161 24178 24178 E AndroidRuntime: 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4128)
```

**Comment by ekigamba** [comment]
Needs further **investigation** to determine if this only happens when the instrumentation test apk is also on the device. This is from the component package name above

**Comment by ekigamba** [comment]
This seems to be related with the test apk from this

```
01-29 12:27:08.690 12941-12941/io.ona.kujaku.test E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: io.ona.kujaku.test, PID: 12941
                                                                    java.lang.RuntimeException: Unable to start service io.ona.kujaku.services.MapboxOfflineDownloaderService@9756943 with Intent { cmp=io.ona.kujaku.test/io.ona.kujaku.services.MapboxOfflineDownloaderService (has extras) }: java.lang.IllegalStateException: Call 'Realm.init(Context)' before calling this method.
```

**Comment by ekigamba** [comment]
I will uninstall the test apk and investigate further
