### ISSUE TITLE
Fix issues related to PATH incompatibility

### ISSUE THREAD

**Issue by ekigamba** [onaio/kujaku#89]
- [x] MapActivity crashing after offline map download started but not visible due to 
- [x] When an Offline Map Service DELETE_ACTION task is done, it should stop holding the queue

**Comment by ekigamba** [comment]
FATAL EXCEPTION: main
              Process: org.smartregister.path, PID: 23410
              java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/org.smartregister.path-2/base.apk)
                  at io.ona.kujaku.notifications.KujakuNotification.createNotification(KujakuNotification.java:86)
                  at io.ona.kujaku.notifications.DownloadProgressNotification.createNotification(DownloadProgressNotification.java:23)
                  at io.ona.kujaku.notifications.KujakuNotification.createNotification(KujakuNotification.java:102)
                  at io.ona.kujaku.notifications.DownloadProgressNotification.createNotification(DownloadProgressNotification.java:23)
                  at io.ona.kujaku.notifications.DownloadProgressNotification.createInitialNotification(DownloadProgressNotification.java:45)
                  at io.ona.kujaku.services.MapboxOfflineDownloaderService.showProgressNotification(MapboxOfflineDownloaderService.java:553)
                  at io.ona.kujaku.services.MapboxOfflineDownloaderService.showProgressNotification(MapboxOfflineDownloaderService.java:567)
                  at io.ona.kujaku.services.MapboxOfflineDownloaderService.access$1500(MapboxOfflineDownloaderService.java:92)
                  at io.ona.kujaku.services.MapboxOfflineDownloaderService$2.onError(MapboxOfflineDownloaderService.java:388)
                  at io.ona.kujaku.downloaders.MapBoxOfflineResourcesDownloader$7.onList(MapBoxOfflineResourcesDownloader.java:497)
                  at com.mapbox.mapboxsdk.offline.OfflineManager$2$1.run(OfflineManager.java:161)
                  at android.os.Handler.handleCallback(Handler.java:751)
                  at android.os.Handler.dispatchMessage(Handler.java:95)
                  at android.os.Looper.loop(Looper.java:154)
                  at android.app.ActivityThread.main(ActivityThread.java:6780)
                  at java.lang.reflect.Method.invoke(Native Method)
                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by jasonrogena** [comment]
Related to https://github.com/onaio/kujaku/issues/90
